"""aa - added external_id to events db

Revision ID: b76ba14a99a7
Revises: e8bd97128674
Create Date: 2026-01-28 22:22:36.670172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b76ba14a99a7'
down_revision = 'e8bd97128674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_events_external_id'), ['external_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_external_id'))
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###
